##
## Golang application makefile
##

# application name
PRG       ?= $(shell basename $$PWD)
SOURCES   ?= *.go */*.go
SOURCEDIR ?= ". app"

# Default config
SHELL      = /bin/bash
OS        ?= linux
ARCH      ?= amd64
DIRDIST   ?= dist
PRGBIN    ?= $(PRG)_$(OS)_$(ARCH)
PRGPATH   ?= $(PRGBIN)
STAMP     ?= $$(date +%Y-%m-%d_%H:%M.%S)
ALLARCH   ?= "linux/amd64 linux/386 windows/amd64 darwin/386"

# Search .git for commit id fetch
GIT_ROOT  ?= $$([ -d ./.git ] && echo "." || { [ -d ../.git ] && echo ".." ; } || { [ -d ../../.git ] && echo "../.." ; })

# Docker setup
CFG      ?= .config
APP_ROOT ?= $$PWD
APP_SITE ?= app.dev.lan
DB_NAME  ?= appdb.db

# ------------------------------------------------------------------------------

##
## Available targets are:
##

# default: show target list
all:
	@grep -A 1 "^##" Makefile

## build and run
run: build
	./$(PRGPATH) --log_level debug

## build and show help
help: build
	./$(PRGPATH) --help

## build and show version
ver: build
	./@$(PRGPATH) --version && echo ""

## build app
build: lint vet $(PRGPATH)

## build app for default arch
$(PRGPATH): $(SOURCES)
	@echo "*** $@ ***"
	@[ -d $(GIT_ROOT)/.git ] && GH=`git rev-parse HEAD` || GH=nogit ; \
GOOS=$(OS) GOARCH=$(ARCH) go build -o $(PRGBIN) -ldflags \
"-X main.Build=$(STAMP) -X main.Commit=$$GH"

## build app for all platforms
buildall: lint vet
	@echo "*** $@ ***"
	@[ -d $(GIT_ROOT)/.git ] && GH=`git rev-parse HEAD` || GH=nogit ; \
for a in "$(ALLARCH)" ; do \
  echo "** $${a%/*} $${a#*/}" ; \
  P=$(PRG)_$${a%/*}_$${a#*/} ; \
  [ "$${a%/*}" == "windows" ] && P=$$P.exe ; \
  GOOS=$${a%/*} GOARCH=$${a#*/} go build -o $$P -ldflags \
  "-X main.Build=$(STAMP) -X main.Commit=$$GH" ; \
done

## create disro files
dist: clean buildall
	@echo "*** $@ ***"
	@[ -d $(DIRDIST) ] || mkdir $(DIRDIST) ; \
sha256sum $(PRG)* > $(DIRDIST)/SHA256SUMS ; \
for a in "$(ALLARCH)" ; do \
  echo "** $${a%/*} $${a#*/}" ; \
  P=$(PRG)_$${a%/*}_$${a#*/} ; \
  [ "$${a%/*}" == "windows" ] && P1=$$P.exe || P1=$$P ; \
  zip "$(DIRDIST)/$$P.zip" "$$P1" README.md ; \
done

## clean generated files
clean:
	@echo "*** $@ ***"
	@for a in "$(ALLARCH)" ; do \
  P=$(PRG)_$${a%/*}_$${a#*/} ; \
  [ "$${a%/*}" == "windows" ] && P=$$P.exe ; \
  [ -f $$P ] && rm $$P || true ; \
done ; \
[ -d $(DIRDIST) ] && rm -rf $(DIRDIST) || true

## run go lint
lint:
	@echo "*** $@ ***"
	@for d in "$(SOURCEDIR)" ; do echo $$d && golint $$d/*.go ; done

## run go vet
vet:
	@echo "*** $@ ***"
	@for d in "$(SOURCEDIR)" ; do echo $$d && go vet $$d/*.go ; done

# ------------------------------------------------------------------------------

# consup setup
define CONFIG_DEF
# config file, generated by make $(CFG)
APP_SITE=$(APP_SITE)
DB_NAME=$(DB_NAME)
endef
export CONFIG_DEF

## docker: restart container
restart: stop start

## docker: start container
start: vars log build
	@echo "*** $@ ***"
	@source $(CFG) && \
fidm rm mode=www name=$$APP_SITE ; \
fidm start mode=www name=$$APP_SITE \
  args_add=--env=DB_NAME=$$DB_NAME \
  args_add=--volume=$(APP_ROOT):/home/app \
  args_add=--volume=$(APP_ROOT)/log/$$APP_SITE:/var/log/supervisor

#  args_add=--volume=$(APP_ROOT)/../../log/$$APP_SITE:/var/log/supervisor

stop: $(CFG)
	@echo "*** $@ ***"
	@source $(CFG) && \
fidm rm mode=www name=$$APP_SITE

stopall: $(CFG)
	@echo "*** $@ ***"
	@source $(CFG) && \
fidm rm -a mode=www name=$$APP_SITE

# ------------------------------------------------------------------------------

test-login:
	@echo "*** $@ ***"
	@source $(CFG) && \
  REQ='{"jsonrpc":"2.0","method":"Auth.Login","id":1,"params":{"login":"$(TEST_USER)","password":"$(TEST_PASS)"}}' ; \
  KEY=$$(curl -s -d "$$REQ"  -H "Content-Type: application/json" "http://$$APP_SITE/api" | jq -r .result.JWT) && \
  [[ "$$KEY" != "null" ]] && curl -H "X-Elfire-Token: Bearer $$KEY" "http://$$APP_SITE/my/" || \
  { echo "Login error" && exit 1 ; }

# ------------------------------------------------------------------------------

vars: $(CFG) ~/.fidmrc

# настройка контейнеров consup
~/.fidmrc:
	@echo "*** $@ ***"
	@echo "cfg[creator]=lekovr" > $@

$(CFG):
	@echo "*** $@ ***"
	@[ -f $@ ] || echo "$$CONFIG_DEF" > $@

log:
	@[ -d log ] || mkdir log

.PHONY: all run ver buildall clean dist link vet

